### PR TITLE
Meta refresh

### PR DESCRIPTION
**Pull request by phpcodex**
When viewing all posts in the users profiles, the meta tags remained
which in turn redirects the users from view a members posts to a topic.

### CODE REVIEW

**Comment by blackcrack** [comment]
it's alive :) \*happy\*
do, you know what's all okey and not :) 👍

**Comment by phpcodex** [comment]
No, not yet, I've just done a pull request and found some conflicts.

**Comment by phpcodex** [comment]
I'm happy with both of those changes, how about we give this project a good kick-start? 👍

**Comment by blackcrack** [comment]
8\) ?kickstart? \*bride grin\*
do, make , keep it up :)))) 👍 

this Board it is only the single one with a real textdb and you don't find no other one like this on the world, if you start up  and hold the line, like it is (an real php textdb board) and update at all so far, also in direction of PHP7 want what's all possible with this (also the speed/quickness if php7), so do it, you the one where also can sign you name in the code if you update anything :)

best regards
blacky

**Comment by phpcodex** [comment]
Well let's put this in to motion then, have an online meeting regarding this project, sort some project management out and start pushing this as you say, in the direction of PHP7. What kind of software do you normally use to collaborate online?

**Comment by halamix2** [comment]
For management I only know Trello.
For discussion we could use Slack, Discord, or maybe just a forum.
I agree that PHP7 is a good way but I'm also concerned if writing the whole thing from scratch wouldn't be faster/safer (some code is from 2002, it's PHP 4.x)

**Comment by phpcodex** [comment]
Okay, I agree with Slack for communication and Trello for project management. :) - I don't suggest a re-write, let's see how far we can take this with bug fixing current issues, log them in Trello, fix them and then migrate to a PHP7 env.

**Comment by halamix2** [comment]
Here you go :)
https://join.slack.com/myupb/shared_invite/MTk3NjIyMzEzNDQyLTE0OTc0NDQ5NTEtM2M3YjEwYWRjYw
https://trello.com/myupb

**Comment by phpcodex** [comment]
Blackcrack, follow the link Halamix gave us, very useful took to collaborate better. We're in communication properly now.

**Comment by blackcrack** [comment]
>What kind of software do you normally use to collaborate online?

me, oh .. i be a bit by Openmandriva, a bit on nextcloud, have build up my PHPFileMirror for give files outside and coding in the landscape around \*bg\* , by the way i skining the one or other thing, like you can view on http://www.blackysgate.net/forum/  and the php-filemirror it's there : http://www.blackysgate.net/phpfilemirror/ but now i have in the next 2 years or so, more less time for it, i must me concentrate  more on the schooling what i now make .. and fresh started, something like a short apprenticeship .. in my 45 years :\ \*fingercrossing to i am able to handle that\*
so far :)

>For discussion we could use Slack, Discord, or maybe just a forum.
 i can build up a forum for that , it's more public and free for all.. like in the old times
on my blackysgate.net/myUPB if you want, blackysgate.net it is in my basement with openmandriva as serversoft.

slack.. huh.. again something why not an old and good postman or some mailinglisting \*g\*
no, really, i have really less time in the next time.. i must try to make a good apprenticeship
to have later a better making money.. and then can i make a bit more as now.. 
only a helper .. or like i can name that ..  there it is a Forum really better, with this it is a better coordination.. and by side directly a "let show how it works" because, we use it by self. Insteat slack or other things .. we can use this what we have .. at moment you are have build up..
or better to say, at moment i am be out so far.. but i can stay still in the group.. and maybe the one or other finger on it.. in github :) maybe later in slack or in the forum, but now.. learning..

best regards
Blacky

**Comment by halamix2** [comment]
It seems that rwchhs already merged that in e48405d36f4155dd72ff86bedb525fd793c27c0d, additionally moving includes/inc/post.in.php to classes/PostingFunctions.php

**Pull request closed without merging**
